# Import Laibraris

In [5]:
## Import 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Load Dataset

In [6]:
df_matches=pd.read_csv("D:\\ipl-gt-vs-rr-data-analytics\\match_summary.csv")
df_players=pd.read_csv("D:\\ipl-gt-vs-rr-data-analytics\\players_master.csv")
df_bowling=pd.read_csv("D:\\ipl-gt-vs-rr-data-analytics\\bowling_stats.csv")
df_deliveries=pd.read_csv("D:\\ipl-gt-vs-rr-data-analytics\\ball_by_ball_datas.csv")
df_players

,match_id,team,player,runs,balls,fours,sixes,strike_rate,status
0,1.0,RR,Y Jaiswal,55.0,36.0,6.0,3.0,152.78,out
1,1.0,RR,V Suryavanshi,31.0,18.0,5.0,1.0,172.22,out
2,1.0,RR,D Jurel,75.0,42.0,5.0,5.0,178.57,out
3,1.0,RR,R Parag,8.0,4.0,0.0,1.0,200.00,out
4,1.0,RR,S Hetmyer,18.0,8.0,1.0,2.0,225.00,out
5,1.0,RR,D Ferreira,1.0,3.0,0.0,0.0,33.33,out
6,1.0,RR,R Jadeja,7.0,7.0,1.0,0.0,100.00,not_out
7,1.0,RR,J Archer,1.0,2.0,0.0,0.0,50.00,not_out
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1.0,GT,B S Sudharsan,73.0,44.0,9.0,3.0,165.91,out
10,1.0,GT,K Kushagra,18.0,14.0,3.0,0.0,128.57,out
11,1.0,GT,J Buttler,26.0,14.0,5.0,0.0,185.71,out
12,1.0,GT,G Phillips,3.0,4.0,0.0,0.0,75.00,out
13,1.0,GT,W Sundar,4.0,2.0,1.0,0.0,200.00,out
14,1.0,GT,R Tewatia,12.0,6.0,1.0,1.0,200.00,out
15,1.0,GT,S Khan,11.0,4.0,1.0,1.0,275.00,run_out
16,1.0,GT,R Khan,24.0,16.0,3.0,0.0,150.00,out
17,1.0,GT,K Rabada,23.0,16.0,1.0,2.0,143.75,not_out
18,1.0,GT,A Sharma,0.0,1.0,0.0,0.0,0.00,not_out

### Show dataset

In [7]:
# Show Data 
#print(df_matches)
print(df_players)
#print(df_bowling)
#print(df_deliveries)

    match_id team         player  runs  balls  fours  sixes  strike_rate  \
0        1.0   RR      Y Jaiswal  55.0   36.0    6.0    3.0       152.78
1        1.0   RR  V Suryavanshi  31.0   18.0    5.0    1.0       172.22
2        1.0   RR        D Jurel  75.0   42.0    5.0    5.0       178.57
3        1.0   RR        R Parag   8.0    4.0    0.0    1.0       200.00
4        1.0   RR      S Hetmyer  18.0    8.0    1.0    2.0       225.00
5        1.0   RR     D Ferreira   1.0    3.0    0.0    0.0        33.33
6        1.0   RR       R Jadeja   7.0    7.0    1.0    0.0       100.00
7        1.0   RR       J Archer   1.0    2.0    0.0    0.0        50.00
8        NaN  NaN            NaN   NaN    NaN    NaN    NaN          NaN
9        1.0   GT  B S Sudharsan  73.0   44.0    9.0    3.0       165.91
10       1.0   GT     K Kushagra  18.0   14.0    3.0    0.0       128.57
11       1.0   GT      J Buttler  26.0   14.0    5.0    0.0       185.71
12       1.0   GT     G Phillips   3.0    4.0    0.0    0.0        75.00
13       1.0   GT       W Sundar   4.0    2.0    1.0    0.0       200.00
14       1.0   GT      R Tewatia  12.0    6.0    1.0    1.0       200.00
15       1.0   GT         S Khan  11.0    4.0    1.0    1.0       275.00
16       1.0   GT         R Khan  24.0   16.0    3.0    0.0       150.00
17       1.0   GT       K Rabada  23.0   16.0    1.0    2.0       143.75
18       1.0   GT       A Sharma   0.0    1.0    0.0    0.0         0.00

     status
0       out
1       out
2       out
3       out
4       out
5       out
6   not_out
7   not_out
8       NaN
9       out
10      out
11      out
12      out
13      out
14      out
15  run_out
16      out
17  not_out
18  not_out

In [8]:
### Basic Data Check
#print(df_matches.head())
#print(df_players.info())
#print(df_deliveries.describe())

## -->  Handel Mising Values

In [9]:
## -->  Handel Mising Values
print(df_matches.isnull().sum())
print(df_players.isnull().sum())
print(df_bowling.isnull().sum())
print(df_deliveries.isnull().sum())

## -->

match_id         0
date             0
team1            0
team2            0
venue            0
toss_winner      0
toss_decision    0
team1_runs       0
team1_wickets    0
team1_overs      0
team2_runs       0
team2_wickets    0
team2_overs      0
winner           0
result_margin    0
dtype: int64
match_id       1
team           1
player         1
runs           1
balls          1
fours          1
sixes          1
strike_rate    1
status         1
dtype: int64
match_id         1
team             1
bowler           1
overs            1
maidens          1
runs_conceded    1
wickets          1
economy          1
dtype: int64
match_id        0
innings         0
over            0
ball            0
batting_team    0
bowler          0
runs            0
extras          0
wicket          0
dtype: int64

## --> Remove Duplicates & Remove NAN rows

In [10]:
## --> Remove Duplicates
df_matches.drop_duplicates(inplace=True)
df_players.drop_duplicates(inplace=True)
df_bowling.drop_duplicates(inplace=True)
df_deliveries.drop_duplicates(inplace=True)
df_players.dropna(how='all',inplace=True)
df_bowling.dropna(how='all',inplace=True)

## --> Fix Data Types

In [25]:
## Fix Data types
#print(df_matches.info())
df_matches['date']=pd.to_datetime(df_matches['date'])

print(df_players.info())
cols=['match_id','runs','balls','fours','sixes']
df_players[cols]=df_players[cols].astype(int)
df_players

print(df_bowling.info())
col=['match_id','maidens','runs','wickets']
df_bowling[col]=df_bowling[col].astype(int)

df_deliveries['runs']=df_deliveries['runs'].astype(int)
print(df_bowling)
df_bowling.rename(columns={'runs_conceded':'runs'},inplace=True)
df_bowling.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18 entries, 0 to 18
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   match_id     18 non-null     int64
 1   team         18 non-null     object
 2   player       18 non-null     object
 3   runs         18 non-null     int64
 4   balls        18 non-null     int64
 5   fours        18 non-null     int64
 6   sixes        18 non-null     int64
 7   strike_rate  18 non-null     float64
 8   status       18 non-null     object
dtypes: float64(1), int64(5), object(3)
memory usage: 1.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 0 to 12
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   match_id  12 non-null     int64
 1   team      12 non-null     object
 2   bowler    12 non-null     object
 3   overs     12 non-null     float64
 4   maidens   12 non-null     int64
 5   runs      12 non-null     int64
 6   wickets   12 non-null     int64
 7   economy   12 non-null     float64
dtypes: float64(2), int64(4), object(2)
memory usage: 864.0+ bytes
None
    match_id team            bowler  overs  maidens  runs  wickets  economy
0          1   RR      Jofra Archer    4.0        0    38        0     9.50
1          1   RR     Nandre Burger    3.0        0    29        1     9.67
2          1   RR    Sandeep Sharma    3.0        0    34        0    11.33
3          1   RR  Tushar Deshpande    3.0        0    24        1     8.00
4          1   RR   Ravindra Jadeja    2.0        0    25        0    12.50
5          1   RR       Riyan Parag    1.0        0    11        1    11.00
6          1   RR      Ravi Bishnoi    4.0        0    41        4    10.25
8          1   GT    Mohammed Siraj    4.0        0    48        1    12.00
9          1   GT     Kagiso Rabada    4.0        0    42        2    10.50
10         1   GT      Ashok Sharma    4.0        0    37        1     9.25
11         1   GT   Prasidh Krishna    4.0        0    43        1    10.75
12         1   GT       Rashid Khan    4.0        0    39        1     9.75
<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 0 to 12
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   match_id  12 non-null     int64
 1   team      12 non-null     object
 2   bowler    12 non-null     object
 3   overs     12 non-null     float64
 4   maidens   12 non-null     int64
 5   runs      12 non-null     int64
 6   wickets   12 non-null     int64
 7   economy   12 non-null     float64
dtypes: float64(2), int64(4), object(2)
memory usage: 864.0+ bytes

## 7) Feature Engineering

#### 7.1) Strike_rate (Recalculate)

In [26]:
df_players['strike_rate']=(df_players['runs'] / df_players['balls'])*100

#### 7.2) bowling Economy

In [27]:
#7.2) bowling Economy 
df_bowling['economy']=df_bowling['runs'] / df_bowling['overs'] 
#df_bowling['economy']=df_bowling['economy'].round(2)
#
df_bowling

    match_id team            bowler  overs  maidens  runs  wickets    economy
0          1   RR      Jofra Archer    4.0        0    38        0   9.500000
1          1   RR     Nandre Burger    3.0        0    29        1   9.666667
2          1   RR    Sandeep Sharma    3.0        0    34        0  11.333333
3          1   RR  Tushar Deshpande    3.0        0    24        1   8.000000
4          1   RR   Ravindra Jadeja    2.0        0    25        0  12.500000
5          1   RR       Riyan Parag    1.0        0    11        1  11.000000
6          1   RR      Ravi Bishnoi    4.0        0    41        4  10.250000
8          1   GT    Mohammed Siraj    4.0        0    48        1  12.000000
9          1   GT     Kagiso Rabada    4.0        0    42        2  10.500000
10         1   GT      Ashok Sharma    4.0        0    37        1   9.250000
11         1   GT   Prasidh Krishna    4.0        0    43        1  10.750000
12         1   GT       Rashid Khan    4.0        0    39        1   9.750000

#### 7.3) Total Runs Per Ball

In [28]:
# Total Runs per ball
df_deliveries['total_runs']=df_deliveries['runs'] + df_deliveries['extras']

#### 7.4) Match Phase Creation

In [29]:
#### 7.4) Match Phase Creation 
def get_phase(over):
    if over <=6:
        return 'Power play'
    elif over <=15:
        return 'Middle'
    else:
        return 'Death'
df_deliveries['match_phase']=df_deliveries['over'].apply(get_phase)

In [30]:
df_deliveries

,match_id,innings,over,ball,batting_team,bowler,runs,extras,wicket,total_runs,match_phase
0,1,1,1,1,RR,Mohammed Siraj,1,0,0,1,Power play
1,1,1,1,2,RR,Mohammed Siraj,4,0,0,4,Power play
2,1,1,1,3,RR,Mohammed Siraj,0,0,0,0,Power play
3,1,1,1,4,RR,Mohammed Siraj,4,0,0,4,Power play
4,1,1,1,5,RR,Mohammed Siraj,1,0,0,1,Power play
...,...,...,...,...,...,...,...,...,...,...,...
245,1,2,20,2,GT,Tushar Deshpande,1,0,0,1,Death
246,1,2,20,3,GT,Tushar Deshpande,1,0,0,1,Death
247,1,2,20,4,GT,Tushar Deshpande,1,0,0,1,Death
248,1,2,20,5,GT,Tushar Deshpande,0,0,1,0,Death
249,1,2,20,6,GT,Tushar Deshpande,0,0,0,0,Death

In [31]:
## 8 ) Validate Clean data 
print(df_players.head())
print(df_deliveries['match_phase'].value_counts())
#df_deliveries.rename(columns={'Match_phase':'match_phase'},inplace=True)

   match_id team         player  runs  balls  fours  sixes  strike_rate status
0         1   RR      Y Jaiswal    55     36      6      3   152.777778    out
1         1   RR  V Suryavanshi    31     18      5      1   172.222222    out
2         1   RR        D Jurel    75     42      5      5   178.571429    out
3         1   RR        R Parag     8      4      0      1   200.000000    out
4         1   RR      S Hetmyer    18      8      1      2   225.000000    out
match_phase
Middle        110
Power play     77
Death          63
Name: count, dtype: int64

# 9) Save Clean data Filse

In [33]:
df_matches.to_csv("D:\clean-ipl-gt-vs-rr-data\clean_matches_summary.csv",index=False)
df_players.to_csv("D:\clean-ipl-gt-vs-rr-data\clean_players_master.csv",index=False)
df_bowling.to_csv("D:\clean-ipl-gt-vs-rr-data\clean_bowling_start_master.csv",index=False)
df_deliveries.to_csv("D:\clean-ipl-gt-vs-rr-data\clean_ball_by_ball_datas.csv",index=False)